// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jycnchyashsvnvbqrvgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5Y25jaHlhc2hzdm52YnFydmdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzgzOTIsImV4cCI6MjA2NTc1NDM5Mn0.tdeduz4cQM55qy65aAbEVZ5nOZ7tULYEbLn1yBlF87w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);